=== geographika/mappyfile/mappyfile/schemas/map.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "additionalProperties": false,
  "patternProperties": {
    "^__[a-z]+__$": {}
  },
  "properties": {
    "__type__": {
      "enum": [ "map" ]
    },
    "include": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "angle": {
      "type": "number",
      "minimum": -360,
      "maximum": 360,
      "default": 0
    },
    "config": {
      "type": "object",
      "properties": {
        "CGI_CONTEXT_URL": { "type": "string" },
        "MS_ENCRYPTION_KEY": { "type": "string" },
        "MS_ERRORFILE": { "type": "string" },
        "MS_NONSQUARE": {
          "$ref": "yesno.json"
        },
        "ON_MISSING_DATA": {
          "type": "string",
          "default": "FAIL",
          "enum": [ "FAIL", "LOG", "IGNORE" ]
        },
        "PROJ_LIB": { "type": "string" }
      },
      "additionalProperties": true
    },
    "datapattern": {
      "type": "string"
    },
    "debug": {
      "default": 0,
      "allOf": [
        {
          "$ref": "debug.json"
        }
      ],
      "metadata": {
        "minVersion": 5.0
      }
    },
    "defresolution": {
      "type": "number",
      "default": 72,
      "minimum": 10,
      "maximum": 1000,
      "metadata": {
        "minVersion": 5.6
      }
    },
    "extent": {
      "$ref": "extent.json"
    },
    "fontset": {
      "type": "string"
    },
    "imagecolor": {
      "$ref": "color.json"
    },
    "imagequality": {
      "type": "integer",
      "metadata": {
        "maxVersion": 7.6
      }
    },
    "imagetype": {
      "default": "png",
      "type": "string"
    },
    "interlace": {
      "oneOf": [
        {
          "$ref": "onoff.json"
        }
      ],
      "metadata": {
        "maxVersion": 7.6
      }
    },
    "layers": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "layer.json"
      }
    },
    "legend": {
      "$ref": "legend.json"
    },
    "maxsize": {
      "default": 4096,
      "type": "integer",
      "minimum": 0
    },
    "name": {
      "default": "MS",
      "type": "string"
    },
    "outputformats": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "outputformat.json"
      }
    },
    "projection": {
      "$ref": "projection.json"
    },
    "querymap": {
      "$ref": "querymap.json"
    },
    "reference": {
      "$ref": "reference.json"
    },
    "resolution": {
      "default": 72,
      "minimum": 10,
      "maximum": 1000,
      "type": "number"
    },
    "scaledenom": {
      "type": "number",
      "minimum": 1,
      "metadata": {
        "minVersion": 5.0
      }
    },
    "scalebar": {
      "$ref": "scalebar.json"
    },
    "shapepath": {
      "type": "string"
    },
    "size": {
      "default": [ -1, -1 ],
      "type": "array",
      "items": {
        "type": "integer"
      },
      "minItems": 2,
      "maxItems": 2
    },
    "status": {
      "default": "on",
      "$ref": "onoff.json"
    },
    "symbolset": {
      "type": "string"
    },
    "symbols": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "symbol.json"
      }
    },
    "templatepattern": {
      "type": "string"
    },
    "transparent": {
      "allOf": [
        {
          "$ref": "onoff.json"
        }
      ],
      "metadata": {
        "maxVersion": 7.6
      }
    },
    "units": {
      "default": "meters",
      "$ref": "units.json"
    },
    "web": {
      "$ref": "web.json"
    },
    "__type__": {
      "type": "string"
    }
  }
}

=== geographika/mappyfile/docs/examples/sample.json
{
    "__type__": "map",
    "extent": [
        -180,
        -90,
        180,
        90
    ],
    "name": "MyMap",
    "web": {
        "__type__": "web",
        "metadata": {
            "wms_enable_request": "*",
            "wms_feature_info_mime_type": "text/html",
            "__type__": "metadata"
        }
    },
    "projection": [
        "init=epsg:4326"
    ],
    "layers": [
        {
            "__type__": "layer",
            "processing": [
                "BANDS=1",
                "CONTOUR_ITEM=elevation",
                "CONTOUR_INTERVAL=20"
            ],
            "extent": [
                -180,
                -90,
                180,
                90
            ],
            "name": "rgb",
            "type": "RASTER",
            "data": "../data/raster/bluemarble.tif",
            "template": "raster.template.html"
        }
    ]
}
